import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {NavBar} from "@/components/NavBar/NavBar";
import {Providers} from "@/app/providers";
import {Footer} from "@/components/Footer/Footer";
import s from "./layout.module.scss";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="dark">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${s.body}`}>
                <Providers>
                    <NavBar/>
                    <div className={s.content}>{children}</div>
                    <Footer/>
                </Providers>
            </body>
        </html>
    );
}
