import Head from "next/dist/shared/lib/head";

export function Header() {
    return <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>;
}
