"use client"

import Head from "next/dist/shared/lib/head";
import {useCharacters} from "@/app/hooks/useCharacters";
import s from "./page.module.css"
import CharacterCard from "@/components/CharacterCard";

export default function Characters() {

const characters = useCharacters()

    return (
        <div className={s.global}>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                {characters && characters.map((character) => (
                    <CharacterCard key={character.id} character={character}/>
                ))}
            </main>
        </div>
    )
}
