"use client"

import Head from "next/dist/shared/lib/head";
import {useEffect, useState} from "react";
import axios from "axios";

export default function Characters() {

    const [characters, setCharacters] = useState<null | CharacterType[]>(null)

    useEffect(() => {
        axios.get('https://rickandmortyapi.com/api/character').then(res => {
            setCharacters(res.data.results)
        })
    }, []);

    return (
        <>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                {characters && characters.map((character) => (
                    <div key={character.id}>{character.name}</div>
                ))}
            </main>
        </>
    )
}

type CharacterType = {
    id: number,
    name: string,
    image: string,
}
